version: "3"

services:
    local-server:
        build: ./images/local-dns
        image: seed-local-dns-server
        container_name: local-dns-server-10.9.0.53
        tty: true
        cap_add:
                - ALL
        networks:
            seed-net:
                ipv4_address: 10.9.0.53
                  
    user:
        build: ./images/seed-user
        image: seed-user
        container_name: user-10.9.0.5
        tty: true
        cap_add:
                - ALL
        networks:
            seed-net:
                ipv4_address: 10.9.0.5

    attacker:
        build: ./images/seed-attacker
        image: seed-attacker
        container_name: seed-attacker
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:..
        network_mode: host

    attacker_ns:
        build: ./images/attacker-ns
        image: seed-attacker_ns
        container_name: attacker-ns-10.9.0.153
        tty: true
        cap_add:
                - ALL
        networks:
            seed-net:
                ipv4_address: 10.9.0.153

networks:
    seed-net:
        name: seed-net
        ipam:
            config:
                - subnet: 10.9.0.0/24

